pod 'Stripe', '~> 4.0'
pod 'Stripe/ApplePay'
pod 'PaymentKit'
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController', :branch => 'version_5.3.2_patch'
pod 'CHTTextView', '~> 0.1'
pod 'LLSimpleCamera', '~> 2.2'
pod 'FormatterKit', '~> 1.8'
pod 'CardIO', '~> 5.0'
pod 'MaveSDK', '~> 0.7.1'
pod 'CWStatusBarNotification', '~> 2.2.6'
pod 'FLAnimatedImage', '~> 1.0'
pod 'CNPPopupController'