pod 'Stripe'
pod 'Stripe/ApplePay'
pod 'PaymentKit'
pod 'Venmo-iOS-SDK', '~>1.3'
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController', :branch => 'version_5.3.2_patch'
pod 'CHTTextView', '~> 0.1'
pod 'LLSimpleCamera', '~> 2.2'
pod 'FormatterKit', '~> 1.8'
pod 'CardIO', '~> 5.0'
pod 'MaveSDK'
pod 'CWStatusBarNotification', '~> 2.2.6'
pod 'FLAnimatedImage', '~> 1.0'
pod 'Ouralabs'